### ISSUE TITLE
Documentation doesn't specify how errors are handled

### ISSUE THREAD

**Issue by hugoduncan** [infermedica/python-api#2]
The documentation makes no mention of how the library treats errors.   Looking at the code, it seems it throws `requests` exceptions for HTTP errors.

**Comment by akszydelko** [comment]
Thank you for reporting this, we will clear it out in the documentation. The library raises its own errors with appropriate messages depending on the error type.
Take a look [here](https://github.com/infermedica/python-api/blob/master/infermedica_api/exceptions.py).
