### ISSUE TITLE
COVID-19 Update

### ISSUE THREAD

**Issue by funsholaniyi** [infermedica/python-api#6]
Can you kindly update it for the COVID-19 updates too?

**Comment by akszydelko** [comment]
Hey,

The current version works with COVID-19 API, but you need to change the API Version while configuring the API object, see: https://github.com/infermedica/python-api#api-version.

Example:
```
import infermedica_api

infermedica_api.configure(
    app_id='YOUR_APP_ID',
    app_key='YOUR_APP_KEY',
    api_version='covid19'
)
```
or
```
import infermedica_api
api = infermedica_api.API(
    app_id='YOUR_APP_ID',
    app_key='YOUR_APP_KEY',
    api_version='covid19'
)
```

Then you use the module as usual. Let us know if that worked for you.

We have on our roadmaps extending the documentation and providing some examples.

**Comment by funsholaniyi** [comment]
Thanks.
